import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import Provider from '@/context/provider';
import { Toaster } from 'sonner';
import Player from '@/components/common/Player';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark bg-black text-white`}
      >
        <Provider>
          <Toaster position="bottom-right" closeButton />
          {children}
          {/* Mounted once here (not per-layout) so the <audio> element, and
              the persistent control bar it renders, survive navigation
              between the dashboard and every other route instead of being
              torn down and rebuilt. */}
          <Player />
        </Provider>
      </body>
    </html>
  );
}
